# Generated by Django 3.1.6 on 2021-05-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210509_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='typeofleave',
            field=models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Maternity', 'Maternity'), ('Annual', 'Annual'), ('Bereavement', 'Bereavement'), ('Compensatory', 'Compensatory ')], default='Annual', max_length=12, null=True),
        ),
    ]
