# Generated by Django 3.1.6 on 2021-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_leave_typeofleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('notapproved', 'notapproved')], default='notapproved', max_length=11, null=True),
        ),
    ]
