# Generated by Django 3.1.6 on 2021-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210511_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='NOleave',
            new_name='leavedatesapplied',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leavesdatesapplied',
        ),
        migrations.AddField(
            model_name='leave',
            name='leavedays',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='leave',
            name='typeofleave',
            field=models.CharField(blank=True, choices=[('Annual', 'Annual')], default='Annual', max_length=12, null=True),
        ),
    ]
