# Generated by Django 3.1.6 on 2021-05-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210512_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='remainingdays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
