# Generated by Django 3.1.6 on 2021-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20210519_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinary',
            options={'verbose_name_plural': 'Disciplinaries'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'skills'},
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('notapproved', 'notapproved')], default='notapproved', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='typeofleave',
            field=models.CharField(blank=True, choices=[('Annual', 'Annual'), ('sick', 'sick'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('bereavement', 'bereavement'), ('bereavement', 'bereavement'), ('unpaid', 'unpaid')], default='Annual', max_length=12, null=True),
        ),
    ]
